name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t kavyanaik/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true kavyanaik/react-test npm test
 
      - run: docker build -t kavyanaik/multi-client ./client
      - run: docker build -t kavyanaik/multi-nginx ./nginx
      - run: docker build -t kavyanaik/multi-server ./server
      - run: docker build -t kavyanaik/multi-worker ./worker
 
      - run: docker push kavyanaik/multi-client
      - run: docker push kavyanaik/multi-nginx
      - run: docker push kavyanaik/multi-server
      - run: docker push kavyanaik/multi-worker